### ISSUE TITLE
Usage against existing plugin

### ISSUE THREAD

**Issue by arichiardi** [cameronkerrnz/logstash-plugin-dev#2]
Hi there,

first of all thanks for this project, it seems like you are filling a gap there cause I was not be able to find any docker image for building logstash plugins.

 I am trying to build locally the `logstash-output-mongo` plugin and I found the following:

```
$ docker run --rm -it -v ${PWD}:/work cameronkerrnz/logstash-plugin-dev:7.9 bundle
/opt/jruby/bin/bundle: line 9: require: command not found
/opt/jruby/bin/bundle: line 11: version: command not found
/opt/jruby/bin/bundle: bundle: line 15: syntax error near unexpected token `('
/opt/jruby/bin/bundle: bundle: line 15: `  str = str.dup.force_encoding("BINARY") if str.respond_to? :force_encoding'
```

Am I doing the right thing?

Thanks again!

**Comment by arichiardi** [comment]
If I execute the command from within the shell (no `bundle install` appended to the `docker run` command), it seems to work.

My requirement though was also to be able to build and include the plugin as part of another docker image so I am trying that now.

**Comment by arichiardi** [comment]
FYI it worked great with the following,

```
FROM cameronkerrnz/logstash-plugin-dev:7.9 as logstash-builder

###############################
# Clone logstash-output-mongo #
###############################

USER root

ARG pluginworkdir=/work/logstash-output-mongodb

RUN git clone https://github.com/iteratec/logstash-output-mongodb \
        --branch feature/implementDifferentActions --single-branch $pluginworkdir
RUN chown builder $pluginworkdir

WORKDIR $pluginworkdir

USER builder
RUN bundle install \
    && bundle exec rspec \
    && gem build logstash-output-mongodb.gemspec
```

Closing this issue cause it seems the `docker run` is not a real blocker.

Thank you!

**Comment by cameronkerrnz** [comment]
Cool; though I think you'll want to use `chown -R builder $pluginworkdir`

Admittedly I haven't really considered the use-case of running this container as a tool, but only as a dev-container, as described in https://github.com/cameronkerrnz/logstash-plugin-dev

Currently /bin/bash is the default entrypoint, which means if you want to run a tool via docker run, remember to pass it as a `-c` (to bash). Eg:

```
docker run --rm -it -v ${PWD}:/work cameronkerrnz/logstash-plugin-dev:7.9
   -c "logstash-plugin generate --type=filter --name=coolstuff --path=/work/"
```

Thanks for your interest.
